package utils

const (
	MAX_EFFECTIVE_INCREMENTS    = 32
	BASE_REWARD_FACTOR          = 64
	BASE_REWARD_PER_EPOCH       = 4
	EFFECTIVE_BALANCE_INCREMENT = 1000000000
	SLOTS_PER_EPOCH             = 32
	SHUFFLE_ROUND_COUNT         = uint64(90)
	PROPOSER_REWARD_QUOTIENT    = 8
	GENESIS_EPOCH               = 0
	SLOTS_PER_HISTORICAL_ROOT   = 8192
)
