CREATE TABLE IF NOT EXISTS t_transactions(
    f_tx_idx SERIAL,
    f_tx_type INT,
    f_chain_id BIGINT,
    f_data TEXT DEFAULT '',
    f_gas BIGINT,
    f_gas_price BIGINT,
    f_gas_tip_cap BIGINT,
    f_gas_fee_cap BIGINT,
    f_value NUMERIC,
    f_nonce BIGINT,
    f_to TEXT DEFAULT '',
    f_hash TEXT PRIMARY KEY,
    f_size BIGINT,
	f_slot INT,
	f_el_block_number INT,
	f_timestamp INT);